name: 'localndr'

services:
    postgres:
        image: postgres:16-alpine
        environment:
            POSTGRES_DB: localndr
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        ports:
            - 5432:5432
        volumes:
            - ./postgres.conf:/etc/postgresql/postgresql.conf:ro
        tmpfs:
            - /var/lib/postgresql/data
            - /tmp
        command:
            - postgres
            - -c
            - config_file=/etc/postgresql/postgresql.conf

    electric:
        image: electricsql/electric
        environment:
            DATABASE_URL: postgresql://postgres:password@postgres:5432/localndr?sslmode=disable
        ports:
            - '3000:3000'
        depends_on:
            - postgres