
--
-- Postgres SQL Schema dump automatic generated by geni
--


-- EXTENSIONS 

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;

-- TABLES 

CREATE TABLE events (
 calendar_id uuid ,
 created_at timestamp with time zone ,
 description text ,
 end_date timestamp with time zone  NOT NULL,
 id uuid  NOT NULL,
 start_date timestamp with time zone  NOT NULL,
 title character varying (255) NOT NULL,
 updated_at timestamp with time zone 
);

CREATE TABLE schema_migrations (
 id character varying (255) NOT NULL
);

-- CONSTRAINTS 

ALTER TABLE events ADD CONSTRAINT events_pkey PRIMARY KEY (id);

ALTER TABLE schema_migrations ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (id);

-- INDEXES 

CREATE UNIQUE INDEX events_pkey ON public.events USING btree (id)

CREATE INDEX idx_events_calendar ON public.events USING btree (calendar_id)

CREATE INDEX idx_events_dates ON public.events USING btree (start_date, end_date)

CREATE UNIQUE INDEX schema_migrations_pkey ON public.schema_migrations USING btree (id)

